name: PR

on:
  pull_request:

jobs:
  lint-pr-title:
    name: Lint (PR Title)
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read # for amannn/action-semantic-pull-request to analyze PRs
      statuses: write # for amannn/action-semantic-pull-request to mark status of analyzed PR
    steps:
      - uses: amannn/action-semantic-pull-request@v5.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
